### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by houxing2279** [winde03/Sx-Attribute-reload#1]
github/saukiya/sxattribute/data/attribute/SXAttributeType initializing SX-MoreAttribute v1.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: github/saukiya/sxattribute/data/attribute/SXAttributeType] 
at github.saukiya.zfattribute.attribute.damage.DamageAttribute.<init>(DamageAttribute.java:39) ~[?:?] 
at github.saukiya.zfattribute.ZFAttribute.onLoad(ZFAttribute.java:56) ~[?:?] 
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:386) [CraftServer.class:2b0299e] 
at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:393) [bfb.class:?] 
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:345) [MinecraftServer.class:?] 
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?] 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587) [MinecraftServer.class:?] 
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] 
Caused by: java.lang.ClassNotFoundException: github.saukiya.sxattribute.data.attribute.SXAttributeType] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:118) ~[PluginClassLoader.class:2b0299e] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PluginClassLoader.class:2b0299e] 
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261] 
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261] 
... 8 more]

**Comment by winde03** [comment]
这个插件有前置插件的
